name = "GlobalDiffEq"
uuid = "1d72d19b-84cc-4cb7-a099-7cbdb9ccc67c"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com> and contributors"]
version = "0.1.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"

[compat]
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
